
import { Language, ScanStepData } from './types';

export const APP_NAME = "ESA SecureScout";

export const UI_TEXT = {
  en: {
    heroTitle: "ESA SecureScout - AI Powered Security",
    heroSubtitle: "Instant, enterprise-grade vulnerability scanning powered by Gemini 3 Pro. Detect threats before they become breaches.",
    placeholder: "Enter website URL (e.g., https://example.com) or paste source code...",
    scanButton: "Scan Now",
    scanning: "Analyzing Security Posture...",
    resultsTitle: "ESA Security Analysis Report",
    riskScore: "Security Score",
    criticalIssues: "Critical Issues",
    improvements: "Improvements",
    exportPdf: "Export to PDF",
    vulnerabilities: "Vulnerabilities",
    fixRecommendation: "Remediation & Code Fix",
    about: "ESA SecureScout uses advanced AI to simulate security assessments. Developed by Eslam Elokpy for educational purposes.",
    themeDark: "Dark",
    themeLight: "Light",
    techStack: "Detected Tech Stack",
    cweReference: "CWE Reference",
    impact: "Potential Impact",
    "re-scan": "New Scan",
    disclaimer: "Disclaimer: This report is generated by AI for educational and preliminary assessment purposes only.",
    cancelScan: "Cancel Scan",
    copyCode: "Copy Code",
    copied: "Copied!",
    // Login Page
    loginTitle: "Sign in to ESA SecureScout",
    loginSubtitle: "Authenticate with Google to access the scanner.",
    signInGoogle: "Sign in with Google",
    // Dashboard Tabs
    tabSecurity: "Security Vulnerabilities",
    tabPerformance: "Performance & SEO",
    tabAccessibility: "Accessibility",
    // Landing Page Specifics
    featuresTitle: "Why Choose ESA SecureScout?",
    howItWorksTitle: "How It Works",
    vulnTitle: "Vulnerabilities We Detect",
    trustedBy: "Powered by Gemini 3 Pro • Developed by Eslam Elokpy",
    features: [
      { title: "AI-Powered Analysis", desc: "Utilizes Gemini 3 Pro reasoning to understand context, not just pattern matching." },
      { title: "Instant Results", desc: "Get a comprehensive security breakdown in seconds, not hours." },
      { title: "Actionable Fixes", desc: "Don't just see the problem. Get copy-paste code snippets to fix it." },
      { title: "Global Support", desc: "Native support for English and Arabic detailed reports." }
    ],
    steps: [
      { title: "Input Target", desc: "Paste your target website URL or source code." },
      { title: "AI Deep Scan", desc: "Our engine analyzes patterns, headers, and logic." },
      { title: "Get Secure", desc: "Receive a detailed report with actionable fixes." }
    ],
    // New Advanced Features
    explainBtn: "Explain with AI",
    educationTitle: "Vulnerability Knowledge Base",
    closeBtn: "Close",
    tickerTitle: "THREAT INTEL",
    developerCredit: "Developed by Eslam Elokpy"
  },
  ar: {
    heroTitle: "ESA SecureScout - أمن سيبراني بالذكاء الاصطناعي",
    heroSubtitle: "فحص فوري للثغرات بمستوى المؤسسات مدعوم بـ Gemini 3 Pro. اكتشف التهديدات قبل حدوثها.",
    placeholder: "أدخل رابط الموقع (مثلاً https://example.com) أو الصق الكود المصدري...",
    scanButton: "افحص الآن",
    scanning: "جاري تحليل الوضع الأمني...",
    resultsTitle: "تقرير ESA للتحليل الأمني",
    riskScore: "درجة الأمان",
    criticalIssues: "مشاكل حرجة",
    improvements: "تحسينات",
    exportPdf: "تصدير كملف PDF",
    vulnerabilities: "الثغرات الأمنية",
    fixRecommendation: "الإصلاح والتوصيات البرمجية",
    about: "يستخدم ESA SecureScout الذكاء الاصطناعي المتقدم لمحاكاة التقييمات الأمنية. تم تطويره بواسطة إسلام العلقبي.",
    themeDark: "داكن",
    themeLight: "فاتح",
    techStack: "التقنيات المكتشفة",
    cweReference: "مرجع CWE",
    impact: "التأثير المحتمل",
    "re-scan": "فحص جديد",
    disclaimer: "إخلاء مسؤولية: تم إنشاء هذا التقرير بواسطة الذكاء الاصطناعي لأغراض تعليمية وتقييم أولي فقط.",
    cancelScan: "إلغاء الفحص",
    copyCode: "نسخ الكود",
    copied: "تم النسخ!",
    // Login Page
    loginTitle: "تسجيل الدخول إلى ESA SecureScout",
    loginSubtitle: "قم بتسجيل الدخول باستخدام Google للوصول إلى الفاحص.",
    signInGoogle: "تسجيل الدخول باستخدام Google",
    // Dashboard Tabs
    tabSecurity: "الثغرات الأمنية",
    tabPerformance: "الأداء و SEO",
    tabAccessibility: "إمكانية الوصول",
    // Landing Page Specifics
    featuresTitle: "لماذا تختار ESA SecureScout؟",
    howItWorksTitle: "كيف يعمل؟",
    vulnTitle: "نكتشف الثغرات التالية",
    trustedBy: "مدعوم بـ Gemini 3 Pro • تم التطوير بواسطة إسلام العلقبي",
    features: [
      { title: "تحليل بالذكاء الاصطناعي", desc: "يستخدم تفكير Gemini 3 Pro لفهم السياق، وليس فقط مطابقة الأنماط." },
      { title: "نتائج فورية", desc: "احصل على تحليل أمني شامل في ثوانٍ، وليس ساعات." },
      { title: "إصلاحات عملية", desc: "لا تكتفِ برؤية المشكلة. احصل على أكواد برمجية جاهزة للإصلاح." },
      { title: "دعم عالمي", desc: "دعم محلي للتقارير التفصيلية باللغتين الإنجليزية والعربية." }
    ],
    steps: [
      { title: "إدخال الهدف", desc: "أدخل رابط الموقع أو الكود المصدري." },
      { title: "فحص عميق", desc: "يقوم محركنا بتحليل الأنماط والرؤوس والمنطق." },
      { title: "احصل على الأمان", desc: "استلم تقريراً مفصلاً مع إصلاحات قابلة للتنفيذ." }
    ],
    // New Advanced Features
    explainBtn: "شرح بالذكاء الاصطناعي",
    educationTitle: "قاعدة معرفة الثغرات",
    closeBtn: "إغلاق",
    tickerTitle: "استخبارات التهديدات",
    developerCredit: "تطوير إسلام العلقبي"
  }
};

export const SCAN_STEPS: Record<Language, ScanStepData[]> = {
  en: [
    { label: "Initiating ESA Scan", subLabel: "Validating target and establishing connection..." },
    { label: "Analyzing Tech Stack", subLabel: "Identifying CMS, frameworks, and server software..." },
    { label: "Deep Heuristic Analysis", subLabel: "Scanning for XSS, SQLi, and logic flaws..." },
    { label: "ESA AI Reasoning", subLabel: "Gemini 3 Pro is contextualizing findings..." },
    { label: "Generating Report", subLabel: "Formulating remediation strategies and fixes..." }
  ],
  ar: [
    { label: "بدء فحص ESA", subLabel: "التحقق من الهدف وإنشاء الاتصال..." },
    { label: "تحليل التقنيات", subLabel: "تحديد نظام إدارة المحتوى وأطر العمل..." },
    { label: "تحليل استدلالي عميق", subLabel: "البحث عن ثغرات XSS و SQLi والأخطاء المنطقية..." },
    { label: "تحليل ESA بالذكاء الاصطناعي", subLabel: "Gemini 3 Pro يقوم بدراسة السياق..." },
    { label: "إعداد التقرير", subLabel: "صياغة استراتيجيات الإصلاح والحلول..." }
  ]
};

export const MOCK_REPORT_DELAY = 2000;

export const TERMINAL_LOGS = [
  "ESA SecureScout initializing...",
  "Authenticating session...",
  "Analyzing SSL/TLS configuration...",
  "Fetching HTTP headers...",
  "Checking Content-Security-Policy...",
  "Scanning for open ports...",
  "Identifying JavaScript frameworks...",
  "Parsing DOM structure...",
  "Searching for reflected XSS vectors...",
  "Testing SQL injection patterns...",
  "Verifying cookie attributes...",
  "Checking for exposed .git directory...",
  "Analyzing API endpoints...",
  "Validating CSRF tokens...",
  "Gemini 3 Pro analyzing logic flows...",
  "Correlating findings with CVE database...",
  "Drafting remediation steps...",
  "Finalizing security score...",
  "ESA Report generation in progress..."
];

export const THREAT_INTEL = [
  { id: 1, type: "CVE", text: "CVE-2025-1337: Critical RCE in common middleware detected" },
  { id: 2, type: "ALERT", text: "New phishing campaign targeting developers" },
  { id: 3, type: "UPDATE", text: "Chrome v135 releases security patches" },
  { id: 4, type: "TREND", text: "Rise in API authorization broken access control" },
  { id: 5, type: "OWASP", text: "A01:2025 - Broken Access Control remains top threat" }
];
